[package]
name = "pokepay-std"
version = "0.1.1"
edition = "2021"
publish = false

[dependencies.lolid]
version = "1.0.6"
features = ["std", "serde", "osrng"]
optional = true

[dependencies.mac_address]
version = "1"
optional = true

[features]
std = []
uuid = ["lolid", "mac_address"]
